version: '3.4'
networks:
  grupoum:
volumes:
  mongo-data:
    external: true
services:
  backend-courses:
    container_name: backend-courses
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - SERVER_PORT=80
    networks:
      - grupoum
    depends_on:
      - database
  database:
    container_name: database-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - grupoum
    volumes:
      - mongo-data:/data/db