server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: courses-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:courses}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:root}
      authentication-database: ${MONGO_AUTHENTICATION_DATABASE:admin}
      uuid-representation: ${MONGO_UUID_REPRESENTATION:standard}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URL:http://localhost:8090/auth}/realms/${KEYCLOAK_REALM:master}
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:client-id}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:secret}
            client-authentication-method: post
            authorization-grant-type: ${KEYCLOAK_GRANT_TYPE:password}
            client-name: ${KEYCLOAK_CLIENT_ID:admin-cli}
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_REALM_URL:http://localhost:8090/auth}/realms/${KEYCLOAK_REALM:master}
            user-name-attribute: preferred_username
            jwk-set-uri: ${KEYCLOAK_REALM_URL:http://localhost:8090/auth}/realms/${KEYCLOAK_REALM:master}/protocol/openid-connect/certs
logging:
  level:
    root: INFO
    constsw:
      grupoum:
        oauth: ${LOGGING_LEVEL:INFO}