spring:
  application:
    name: courses-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: courses
      username: root
      password: root
      authentication-database: admin
      uuid-representation: standard
logging:
  level:
    root: INFO
    constsw:
      grupoum:
        oauth: ${LOGGING_LEVEL:INFO}