spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true # http://localhost:8080/h2-console
  jpa:
    defer-datasource-initialization: true