spring:
  application:
    name: courses-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: courses
      username: root
      password: root
      authentication-database: admin
      uuid-representation: standard
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URL:http://localhost:8090/auth}/realms/master
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:zFHd3nu9XA3L0ULdxJPZ3EVeRKflrgbg}
            client-authentication-method: post
            authorization-grant-type: password
            client-name: admin-cli
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_REALM_URL:http://localhost:8090/auth}/realms/master
            user-name-attribute: preferred_username
            jwk-set-uri: ${KEYCLOAK_REALM_URL:http://localhost:8090/auth}/realms/master/protocol/openid-connect/certs
logging:
  level:
    root: INFO
    constsw:
      grupoum:
        oauth: ${LOGGING_LEVEL:INFO}